apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: eva-templates
  description: Golden path templates for the Nerv platform
spec:
  targets:
    - ./templates/go-service/template.yaml
    - ./templates/brm-custom-fm/template.yaml
    - ./templates/brm-policy-override/template.yaml