#!/usr/bin/env bash
# Stages Oracle's stock policy source and routes opcodes to our wrappers.
#
# Usage: scripts/route-overrides.sh <overrides.conf> <stage-dir>
#
# For each "<opcode> <wrapper>" line of overrides.conf, finds the one
# $PIN_HOME/source/sys/fm_*_pol library whose config table registers the
# opcode, copies its source into <stage-dir>, and replaces the function name in
# that table entry with the wrapper.
#
# It stops instead of guessing when an opcode is registered anywhere but
# exactly once. That is how an SDK upgrade that changes the stock source shows
# up: as a failed build, not a CM that silently runs the stock policy.
#
# Writes <stage-dir>/LIBRARY (the library to build), <stage-dir>/ROUTED
# ("<opcode> <stock function> <wrapper>" per line) and <stage-dir>/policy_ops.h
# (the opcode headers the stock config table includes, for the wrappers).
set -euo pipefail

conf="$1"
stage="$2"
sources="${PIN_HOME:-/oms}/source/sys"

fail() {
  echo "route-overrides: $*" >&2
  exit 1
}

rm -rf "$stage"
mkdir -p "$stage"
: > "${stage}/ROUTED"

library=""
while read -r opcode wrapper extra; do
  case "$opcode" in
    '' | '#'*) continue ;;
  esac
  if [ -z "$wrapper" ] || [ -n "$extra" ]; then
    fail "expected \"<opcode> <wrapper>\", got: ${opcode} ${wrapper} ${extra}"
  fi
  [[ "$opcode" =~ ^PCM_OP_[A-Z0-9_]+$ ]] || fail "not an opcode: ${opcode}"
  [[ "$wrapper" =~ ^[a-z_][a-z0-9_]*$ ]] || fail "not a C function name: ${wrapper}"

  # Config table entries look like: { PCM_OP_CUST_POL_VALIDATE, "op_cust_pol_validate" },
  entries=$(grep -Hw -- "$opcode" "$sources"/fm_*_pol/fm_*_pol_config.c | grep '"' || true)
  count=$(printf '%s' "$entries" | grep -c '' || true)
  if [ "$count" -ne 1 ]; then
    fail "${opcode} is registered ${count} times in ${sources}/fm_*_pol/*_config.c, expected once"
  fi

  file="${entries%%:*}"
  lib=$(basename "$(dirname "$file")")
  if [ -z "$library" ]; then
    library="$lib"
    cp -R "${sources}/${lib}/." "$stage"
    rm -f "${stage}/Makefile" "${stage}"/*.o "${stage}"/*.so
  elif [ "$lib" != "$library" ]; then
    fail "${opcode} is in ${lib}, but ${library} is already routed. Create another repository for ${lib}."
  fi

  config="${stage}/$(basename "$file")"
  stock=$(grep -w -- "$opcode" "$config" | grep -o '"[A-Za-z0-9_]*"' | tr -d '"')
  sed -i "/\\b${opcode}\\b/ s/\"${stock}\"/\"${wrapper}\"/" "$config"
  if [ "$(grep -w -- "$opcode" "$config" | grep -c "\"${wrapper}\"")" -ne 1 ]; then
    fail "could not route ${opcode} to ${wrapper} in ${config}"
  fi

  echo "${opcode} ${stock} ${wrapper}" >> "${stage}/ROUTED"
  echo "Routed ${opcode}: ${stock} -> ${wrapper} (${library})"
done < "$conf"

[ -n "$library" ] || fail "no opcodes in ${conf}"
echo "$library" > "${stage}/LIBRARY"

{
  echo "/* Generated by scripts/route-overrides.sh: the opcode headers of ${library}. */"
  grep -h '^#include "ops/' "${stage}/${library}_config.c" || true
} > "${stage}/policy_ops.h"
