apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  labels:
    app.kubernetes.io/name: ${{ values.name }}
    backstage.io/kubernetes-id: ${{ values.name }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ${{ values.name }}
  ports:
    - name: pcm
      port: 11960
      targetPort: pcm
